### ISSUE TITLE
UA - Ultra Exit Request handling in automations

### ISSUE THREAD

**Issue by Flain16** [imhotep/hass-unifi-access#78]
**Is your feature request related to a problem? Please describe.**
I want to have a HomeAssistant automation running when the ua ultra is unlocked, this works fine when you try using: Actor != N/A

**Describe the solution you'd like**
It would be nice to have actor == Exist request or somthing, due to the reason there is no way (as i know, teach me if i am wrong) to decide whether an request is denied cause actor == N/A, an a request is approved due to exit button is beeing pressed (Actor == N/A)

**Describe alternatives you've considered**
tried using other attributes of the entity but did not find some one usefull

**Comment by imhotep** [comment]
Why not use the state automation like so:

```YAML
platform: state
entity_id:
  - lock.MYDOOR # replace this with your entity
from: locked
to: unlocked
```
